package ums.util;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import ums.entity.User;

public class UserTableModel extends AbstractTableModel {
	/**
	 * Generated by VSCode
	 */
	private static final long serialVersionUID = -3549053773085114291L;

	public static final String[] COLUMN_NAMES = { "序号", "Email", "用户名", "性别", "爱好" };

	private final List<User> users;

	public UserTableModel(final List<User> users) {
		this.users = users;
	}

	@Override
	public int getColumnCount() {
		return COLUMN_NAMES.length;
	}

	@Override
	public int getRowCount() {
		return users.size();
	}

	@Override
	public Object getValueAt(final int row, final int col) {
		final User user = users.get(row);
		switch (col) {
			case 0:
				return Integer.toString(row + 1);
			case 1:
				return user.getEmail();
			case 2:
				return user.getUserName();
			case 3:
				return user.getSex();
			case 4:
				return user.getHobbies();
		}
		return null;
	}

	@Override
	public String getColumnName(final int col) {
		return COLUMN_NAMES[col];
	}
}
