package ums.util;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import ums.entity.User;

public class UserTableModel extends AbstractTableModel {
	/**
	 * Generated by VSCode
	 */
	private static final long serialVersionUID = -3549053773085114291L;

	private List<User> users;

	private final int COLUMN_COUNT = 5;

	public UserTableModel(List<User> users) {
		this.users = users;
	}

	public int getColumnCount() {
		return COLUMN_COUNT;
	}

	public int getRowCount() {
		return users.size();
	}

	public Object getValueAt(int row, int col) {
		User user = users.get(row);
		switch (col) {
			case 0:
				return Integer.toString(row + 1);
			case 1:
				return user.getEmail();
			case 2:
				return user.getUserName();
			case 3:
				return user.getSex();
			case 4:
				return user.getHobbies();
		}
		return null;
	}

	public String getColumnName(int col) {
		switch (col) {
			case 0:
				return "序号";
			case 1:
				return "Email";
			case 2:
				return "用户名";
			case 3:
				return "性别";
			case 4:
				return "爱好";
		}
		return null;
	}
}
