package ums.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import ums.dao.UserDao;
import ums.entity.User;

public class ModifyDialog extends JDialog {
    /**
     * Generated by VSCode
     */
    private static final long serialVersionUID = 1703561651461942165L;

    private final UserDao userDao;

    private final JLabel labelEmail = new JLabel("用户 Email");
    private final JTextField textFieldUserEmail = new JTextField(20);
    private final JButton buttonModify = new JButton("修改注册信息");

    private final int windowHeight = 150;
    private final int windowWidth = 400;

    private final JFrame parent;

    public ModifyDialog(final JFrame parent, final String msg, final UserDao userDao) {
        super(parent, msg, true);
        this.parent = parent;
        this.userDao = userDao;

        final JPanel panel = new JPanel();
        panel.add(labelEmail);
        panel.add(textFieldUserEmail);
        panel.add(buttonModify);
        this.add(panel);

        buttonModify.addActionListener(new ButtonModifyHandler());
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        this.setPosition();
        this.validate();
    }

    private void setPosition() {
        final int parentX = parent.getX();
        final int parentY = parent.getY();
        final int parentWidth = parent.getWidth();
        final int parentHeight = parent.getHeight();
        final int dialogX = parentX + (parentWidth - windowWidth) / 2;
        final int dialogY = parentY + (parentHeight - windowHeight) / 2 + 40;
        this.setBounds(dialogX, dialogY, windowWidth, windowHeight);
    }

    private class ButtonModifyHandler implements ActionListener {
        public void actionPerformed(final ActionEvent e) {
            final String userEmail = textFieldUserEmail.getText();
            if (userEmail == null || userEmail.isEmpty()) {
                JOptionPane.showMessageDialog(null, "请输入要修改用户的 Email", "提示", JOptionPane.PLAIN_MESSAGE);
                return;
            }

            final User user = userDao.selectByEmail(userEmail);
            if (user == null) {
                JOptionPane.showMessageDialog(null, "没有该用户", "提示", JOptionPane.PLAIN_MESSAGE);
                return;
            }

            ModifyDialog.this.setVisible(false);
            new RegisterDialog(parent, "修改注册信息", userDao, user).setVisible(true);
        }
    }
}