package ums.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import ums.dao.UserDao;
import ums.entity.User;

public class SearchDialog extends JDialog {
	/**
	 * Generated by VSCode
	 */
	private static final long serialVersionUID = 8595408149994475854L;

	private final UserDao userDao;

	private final JLabel labelName = new JLabel("Email");
	private final JTextField textFieldUserEmail = new JTextField(20);
	private final JButton buttonSearch = new JButton("查询");

	private final int windowHeight = 120;
	private final int windowWidth = 400;

	private final JFrame parent;

	public SearchDialog(final JFrame parent, final String msg, final UserDao userDao) {
		super(parent, msg, true);
		this.parent = parent;
		this.userDao = userDao;

		final JPanel panel = new JPanel();
		panel.add(labelName);
		panel.add(textFieldUserEmail);
		panel.add(buttonSearch);
		this.add(panel);

		buttonSearch.addActionListener(new ButtonSearchByEmailHandler());
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		
		this.setPosition();
		this.validate();
	}

	private void setPosition() {
		final int parentX = parent.getX();
		final int parentY = parent.getY();
		final int parentWidth = parent.getWidth();
		final int parentHeight = parent.getHeight();
		final int dialogX = parentX + (parentWidth - windowWidth) / 2;
		final int dialogY = parentY + (parentHeight - windowHeight) / 2 + 40;
		this.setBounds(dialogX, dialogY, windowWidth, windowHeight);
	}

	private class ButtonSearchByEmailHandler implements ActionListener {
		public void actionPerformed(final ActionEvent e) {
			if (textFieldUserEmail.getText() == null || textFieldUserEmail.getText().length() == 0) {
				JOptionPane.showMessageDialog(null, "请输入要查询用户的email", "提示", JOptionPane.PLAIN_MESSAGE);
				return;
			}

			final User user = userDao.selectByEmail(textFieldUserEmail.getText());

			if (user == null) {
				JOptionPane.showMessageDialog(null, "该用户不存在", "提示", JOptionPane.PLAIN_MESSAGE);
				return;
			}

			final List<User> resList = new ArrayList<User>();
			resList.add(user);
			new ShowDataTableDialog(parent, "查询结果", resList).setVisible(true);
		}
	}
}
