package ums.gui;

import java.util.List;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import ums.entity.User;
import ums.util.UserTableModel;

public class ShowDataTableDialog extends JDialog {
    /**
     * Generated by VSCode
     */
    private static final long serialVersionUID = -965888570630889640L;

    private final int windowHeight = 300;
    private final int windowWidth = 450;

    private final JTable table = new JTable();
    private final JFrame parent;

    public ShowDataTableDialog(final JFrame parent, final String msg, final List<User> users) {
        super(parent, "用户列表", true);
        this.parent = parent;

        table.setModel(new UserTableModel(users));
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        final int column_width[] = { 30, 100, 60, 60, 200 };
        for (int i = 0; i < column_width.length; ++i) {
            table.getColumn(UserTableModel.COLUMN_NAMES[i]).setPreferredWidth(column_width[i]);
        }

        this.add(new JScrollPane(table));

        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        this.setPosition();
        this.validate();
    }

    private void setPosition() {
        final int parentX = parent.getX();
        final int parentY = parent.getY();
        final int parentWidth = parent.getWidth();
        final int parentHeight = parent.getHeight();
        final int dialogX = parentX + (parentWidth - windowWidth) / 2;
        final int dialogY = parentY + (parentHeight - windowHeight) / 2 + 40;
        this.setBounds(dialogX, dialogY, windowWidth, windowHeight);
    }
}
