package gui;

import javax.swing.*;
import java.awt.event.*;

public class EmailInput extends JFrame {

    public static void main(String[] args) {
        new EmailInput().setVisible(true);
    }

    /** Generated by VSCode */
    private static final long serialVersionUID = 1014638151019291945L;

    private final JTextField emailTextField;
    private final JTextField userNameTextField;

    public EmailInput() {

        this.userNameTextField = new JTextField(20);

        JPanel userNamePanel = new JPanel();
        userNamePanel.add(new JLabel("用户名"));
        userNamePanel.add(this.userNameTextField);

        this.emailTextField = new JTextField(20);

        JPanel emailPanel = new JPanel();
        emailPanel.add(new JLabel("Email"));
        emailPanel.add(this.emailTextField);

        JPanel panel = new JPanel();
        panel.add(userNamePanel);
        panel.add(emailPanel);
        this.add(panel);

        this.setBounds(300, 200, 300, 120);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        this.userNameTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (!EmailInput.this.isShowing()) {
                    return;
                }

                String userNameRegex = "[a-zA-Z0-9_]{6,8}";
                String userName = userNameTextField.getText();
                if (!userName.isEmpty() && !userName.matches(userNameRegex)) {
                    String message = "用户名要求是字母、数字和下划线组成的6~8个字符";
                    JOptionPane.showMessageDialog(EmailInput.this, message, "错误", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        this.emailTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (!EmailInput.this.isShowing()) {
                    return;
                }

                String emailRegex = "[a-zA-Z0-9_+\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z0-9]{2,4}";
                String email = emailTextField.getText();
                if (!email.isEmpty() && !email.matches(emailRegex)) {
                    String message = "无效 Email";
                    JOptionPane.showMessageDialog(EmailInput.this, message, "错误", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        this.validate();
    }

}