package gui;

import javax.swing.*;
import javax.swing.event.*;

import java.awt.BorderLayout;
import java.awt.event.*;

public class TextSave extends JFrame {
    public static void main(String[] args) {
        new TextSave().setVisible(true);
    }

    /** Generated by VSCode */
    private static final long serialVersionUID = 8438557937255020235L;

    private final JTextArea textArea;
    private final JButton saveButton;
    private boolean isChanged = false;

    public TextSave() {
        this.textArea = new JTextArea(5, 25);
        this.saveButton = new JButton("保存");

        JPanel panel = new JPanel();
        panel.add(this.textArea, BorderLayout.CENTER);
        panel.add(saveButton, BorderLayout.SOUTH);
        this.add(panel);

        this.setBounds(300, 200, 300, 160);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        this.saveButton.setEnabled(this.isChanged);

        this.textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
                TextSave.this.isChanged = true;
                saveButton.setEnabled(true);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                TextSave.this.isChanged = true;
                saveButton.setEnabled(true);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });

        this.saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                TextSave.this.isChanged = false;
                saveButton.setEnabled(false);
            }
        });

        this.validate();
    }
}