package ums;

import java.util.Scanner;

public class Application {
    private UserDao userDao;

    public void registe() {
        Scanner sc = new Scanner(System.in);

        String userName = null;
        String password = null;

        for (;;) {
            System.out.println("******注册用户******");

            System.out.print("请输入用户名：");
            userName = sc.nextLine();

            System.out.print("请输入密码：");
            password = sc.nextLine();

            System.out.print("请重新输入密码：");
            String password2 = sc.nextLine();

            if (!password.equals(password2)) {
                System.out.println("两次输入的密码不相符，请重新输入！");
                continue;
            } else {
                break;
            }
        }

        boolean ret = userDao.addUser(new User(userName, password));
        if (!ret) {
            System.out.println("错误：用户重复，或系统达到限制。");
            return;
        }

        System.out.printf("%s，注册成功！\n", userName);

    }

    public void login() {
        Scanner sc = new Scanner(System.in);
        System.out.println("******登录******");
        System.out.print("请输入用户名：");
        String userName = sc.nextLine();
        System.out.print("请输入密码：");
        String password = sc.nextLine();
        User user = userDao.getUser(userName, password);
        if (user == null) {
            System.out.println("错误：用户不存在或密码错误。");
        } else {
            System.out.printf("%s 已登录\n", user.getUserName());
        }
    }

    // ------------ Generated by vscode ----------

    public Application(UserDao userDao) {
        this.userDao = userDao;
    }

    public void setUserDao(UserDao userDao) {
        this.userDao = userDao;
    }

}