package restaurant;

public class BadFoodException extends Exception {

    /**
     * Generated by VSCode
     */
    private static final long serialVersionUID = -8048263555233799829L;

    public BadFoodException() {
    }

    public BadFoodException(String msg) {
        super(msg);
    }

}